apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-engine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: base/argocd
