apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./gitops.yaml
- ./policies.yaml

namePrefix: cluster-

patches:
- path: ./patch-gitops.yaml
  target:
    kind: Application
    group: argoproj.io
