apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: na
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
