---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-system
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: base/gatekeeper/system
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
    - /webhooks/1/clientConfig/caBundle
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: base/gatekeeper/constraints
  destination:
    server: https://kubernetes.default.svc
    namespace: default
