---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-namespaces
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
  source:
    repoURL: https://github.com/codeformio/k8s-cluster-config.git
    path: non-prod/apps/greeter
    targetRevision: non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-staging
  namespace: argocd
spec:
  project: app-greeter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
  source:
    repoURL: https://github.com/codeformio/k8s-greeter-app.git
    path: deploy/staging
    targetRevision: non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: greeter-staging
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: greeter-feature-x
  namespace: argocd
spec:
  project: app-greeter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
  source:
    repoURL: https://github.com/codeformio/k8s-greeter-app.git
    path: deploy/feature-x
    targetRevision: non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: greeter-feature-x

