apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: greeter
  namespace: argocd
spec:
  description: Greeter application greets people.
  sourceRepos:
  - 'https://github.com/codeformio/*'
  # Only permit applications to deploy to the greeter namespace in the same cluster
  destinations:
  - namespace: greeter
    server: https://kubernetes.default.svc
  - namespace: greeter-*
    server: https://kubernetes.default.svc
  # Deny cluster scoped resources.
  clusterResourceWhitelist: []
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy
