# Self-manage this directory via GitOps.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
  source:
    repoURL: https://github.com/codeformio/k8s-gitops-config.git
    targetRevision: non-prod
    path: non-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
